services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: ${CONTAINER_NAME}-mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"
    restart: "on-failure"
    networks:
      - my_network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: ${CONTAINER_NAME}-wordpress
    ports:
      - "9000"
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    restart: "on-failure"
    networks:
      - my_network
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: ${CONTAINER_NAME}-nginx
    ports:
      - "443:443" #host:container
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    restart: "on-failure"
    networks:
      - my_network
    depends_on:
      - wordpress

networks:
  my_network:
    name: inception
    driver: bridge

volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      # device: /home/shinckel/data/wp_data
      device: /home/ubuntu/data/wp_data # directory in my personal computer
      o: bind
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      # device: /home/shinckel/data/db_data
      device: /home/ubuntu/data/db_data
      o: bind