# image: nginx:1.15.12-alpine
# - ./data/nginx:/etc/nginx/conf.d
# - "8080:80"
# it is a serialized docker run command
services:
  nginx:
    build: ./requirements/nginx
    container_name: ${CONTAINER_NAME}-nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: ${CONTAINER_NAME}-wordpress
    ports:
      - "9000"
    # env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "coffee"
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - mysql

  mysql:
    build: ./requirements/mysql
    container_name: ${CONTAINER_NAME}-mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "coffee"
    volumes:
      - wp_data:/var/www/html

networks:
  my_network:
    name: inception
    driver: bridge

volumes:
  wp_data:
    #set to local to stored the volume on the host machine
    driver: local
    driver_opts:
      type: none
      # device in my local machine
      # device: /home/ubuntu/data/wp_data
      device: ../data/wp_data
      o: bind
