# defining and running multi-container applications
# simplifies the control of the entire application stack...
# ...manage services, networks, and volumes in a single YAML config file
# srcs/docker-compose.yml

# srcs/docker-compose.yml
# version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "8080:80"
    volumes:
      - ./requirements/nginx/html:/usr/share/nginx/html
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:

# version: '3.8'

# services:
#   mariadb:
#     build: ./requirements/mariadb
#     container_name: mariadb
#     environment:
#       MYSQL_ROOT_PASSWORD: my-secret-pw
#       MYSQL_DATABASE: wordpress
#     volumes:
#       - mariadb_data:/var/lib/mysql
#     networks:
#       - wordpress-network
#     restart: always

#   wordpress:
#     build: ./requirements/wordpress
#     container_name: wordpress
#     environment:
#       WORDPRESS_DB_HOST: mariadb
#       WORDPRESS_DB_USER: root
#       WORDPRESS_DB_PASSWORD: my-secret-pw
#       WORDPRESS_DB_NAME: wordpress
#     volumes:
#       - wordpress_data:/var/www/html
#     networks:
#       - wordpress-network
#     restart: always

#   nginx:
#     build: ./requirements/nginx
#     container_name: nginx
#     ports:
#       - "443:443"
#     volumes:
#       - ./requirements/nginx/ssl:/etc/nginx/ssl
#     networks:
#       - wordpress-network
#     restart: always

# volumes:
#   mariadb_data:
#   wordpress_data:

# networks:
#   wordpress-network: